name: mobile
description: "A new Flutter project."

publish_to: "none"
version: 1.8.1+3

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  darq: ^2.0.0
  dartz: ^0.10.1
  device_info_plus: ^10.0.1
  device_preview: ^1.1.0
  dio: ^5.4.2+1
  easy_localization: ^3.0.5
  envied: ^0.5.4
  equatable: ^2.0.5
  firebase_analytics: ^10.9.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.27.2
  firebase_crashlytics: ^3.4.20
  firebase_messaging: ^14.7.21
  firebase_performance: ^0.9.3+19
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.6
  flutter_bloc: ^8.1.5
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.0.0
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  geolocator: ^11.0.0
  get_it: ^7.6.7
  go_router: ^13.2.2
  google_sign_in: ^6.2.1
  http: ^1.2.1
  injectable: ^2.4.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  isar: ^3.1.0+1
  json_annotation: ^4.8.1
  location: ^5.0.3
  logger: ^2.3.0
  lottie: ^3.1.0
  permission_handler: ^11.3.1
  share_plus: ^8.0.2
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.0
  smooth_page_indicator: ^1.1.0
  stacked_services: ^1.5.0
  url_launcher: ^6.2.5
  web3modal_flutter: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  change_app_package_name: ^1.1.0
  envied_generator: ^0.5.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  injectable_generator: ^2.4.2
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/social-auth-logos/
    - assets/animations/
    - assets/animations/
    - assets/lottie/
    - assets/fonts/
    - assets/wallet-logos/
    - assets/chain-logos/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
