// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlRHo6V70qc_8vOtPoA0rkLt567GdNVik',
    appId: '1:307052986452:android:ff8ecdb5b6b73645f66dc1',
    messagingSenderId: '307052986452',
    projectId: 'hidemeplease-9a0dd',
    storageBucket: 'hidemeplease-9a0dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-CFFZKqWwrlrpnij-Q-zzkWoeZTdQAw4',
    appId: '1:307052986452:ios:f277f56ccf5c184ef66dc1',
    messagingSenderId: '307052986452',
    projectId: 'hidemeplease-9a0dd',
    storageBucket: 'hidemeplease-9a0dd.appspot.com',
    androidClientId: '307052986452-0tm1e9fo0uka8hkrkhle92fp1jvakaot.apps.googleusercontent.com',
    iosClientId: '307052986452-nbhra1i8igok1bnjs6iq3ohiuj1bqmth.apps.googleusercontent.com',
    iosBundleId: 'com.kr.hideme',
  );
}
